"""Criação inicial do banco de dados

Revision ID: 12134a90f643
Revises: 
Create Date: 2025-03-03 12:42:45.899479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12134a90f643'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('CPF', sa.Integer(), nullable=False),
    sa.Column('contato', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('bairro', sa.String(length=120), nullable=False),
    sa.Column('endereco', sa.String(length=120), nullable=False),
    sa.Column('imagem', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imoveis')
    op.drop_table('usuario')
    # ### end Alembic commands ###
